### PR TITLE
Image caching (wip)

### PR DESCRIPTION
**Pull request by taggrx**

### CODE REVIEW

**Comment by taggrx** [comment]
A new insight: the url actually works on my machine, because `curl http://h2uti-feaaa-aaaaa-qaava-cai.raw.localhost:8080/image?offset=8&len=28512 --output pic.jpg` actually returns the correct picture, but in a browser (Safari & Chrome) I get a consistent 404...

**Comment by taggrx** [comment]
New insight: everything works as expected if one does not run `npm start`... Apparently this starts something that hijacks all requests to other canisters. @ulan how did you test it locally? With or without `npm start`?

**Comment by taggrx** [comment]
Ok, I made it work with this hack: https://github.com/TaggrNetwork/taggr/pull/279/commits/36bcb2284e06ee01c073e9cd3b0915391b30811e

**Comment by ulan** [comment]
> New insight: everything works as expected if one does not run `npm start`... Apparently this starts something that hijacks all requests to other canisters. @ulan how did you test it locally? With or without `npm start`?

I tested without `npm start`.

**Comment by ulan** [comment]
> Ok, I made it work with this hack: [36bcb22](https://github.com/TaggrNetwork/taggr/commit/36bcb2284e06ee01c073e9cd3b0915391b30811e)

Interesting! I thought that the `canisterId=N` approach checks the certificate, that's why I changed to `canisterId.raw.localhost`.

**Pull request closed without merging**
