### PR TITLE
Fix colors on android

### PR DESCRIPTION
**Pull request by taggrx**
I had a chance to check out Taggr on Android this weekend. I think this should improve the colors for the app.

### CODE REVIEW

**Review by chmllr — APPROVED** [review]

**Review by nathanosdev — APPROVED** [review]

**Comment by taggrx** [comment]
I added a tiny fix on top: moving out of realms should only work on root posts.

**Comment by taggrx** [comment]
It does, but I have admin priveleges which I can't disable and sometimes misuse 😂 for cases where it's obviously not breaking anything and even if it is, we'll see a broken master and no release can be created. This is the only reason I allow myself to do it to save time.

**Comment by taggrx** [comment]
And of course I can stop doing that if it makes you uncomfortable, really, no problems with that.

**Comment by taggrx** [comment]
Even worse 🙈 I sometimes push directly to master, like I just did: https://github.com/TaggrNetwork/taggr/commit/a674f91c088caa831745fd3a105f2218c4b97504 

But this is more to not annoy you guys with my stupid mistakes. And because when comparing the releases all changes are visible anyway.  I always feel bad for pushing so many changes through you 😏

**Comment by nathanosdev** [comment]
You really shouldn't feel bad for pushing changes through. By spreading the responsibility for the deployed changes among a few developers we're making the Taggr platform, DAO, and community safer.

I was just curious how it was going through anyway. As long as the build passes on master before a release is proposed then I'm happy and my main reason for that is to just make sure that the DAO doesn't suffer our silly mistakes :)

**Pull request merged**
