### PR TITLE
Release

### PR DESCRIPTION
**Pull request by xqxpx**
Implements the dynamic auction sizing: if the price goes up, Taggrs starts minting more tokens and vice versa.

### CODE REVIEW

**Review by chmllr — APPROVED** [review]
LGTM

**Comment by aligatorr89** [comment]
Code looks good, Auctionable amount correctly re-adjusts to weighted price offered in auction. Apart from small diff, probably due to some fees not being counted somewhere.

In example we have auction bids: 0.62ic for 4taggr and 0.6ic for 11 taggr. Result should be 9.08ICP revenue, but it shows 9.07970000 ICP. **EDIT:** this one is ok, fees should be subtracted

Market price should be  0.605333_, but it shows as 0.6051333.  Fees shouldn't account. Big nitpick though

image

**Review by aligatorr89 — APPROVED** [review]

**Comment by aligatorr89** [comment]
> Code looks good, Auctionable amount correctly re-adjusts to weighted price offered in auction. Apart from small diff, probably due to some fees not being counted somewhere.
> 
> In example we have auction bids: 0.62ic for 4taggr and 0.6ic for 11 taggr. Result should be 9.08ICP revenue, but it shows 9.07970000 ICP.
> 
> Similar market price should be 0.605333_, but it shows as 0.6051333.
> 
> image

To clarify, it's must be due to ICP fees. Each tx costs 0.0001 plus one to treasury, thus we get 0.0003 diff. I think market_price shouldn't account for fees, while revenue is correct to subtract it. Big nitpick though :)

**Comment by xqxpx** [comment]
@aligatorr89 thanks so much for the review! 

> Market price should be 0.605333_, but it shows as 0.6051333. Fees shouldn't account

Doesn't it depend on the perspective? I guess I assumed the market price is derived from the actual value landing in Dao's wallet, after subtracting all costs.

**Comment by aligatorr89** [comment]
> @aligatorr89 thanks so much for the review!
> 
> > Market price should be 0.605333_, but it shows as 0.6051333. Fees shouldn't account
> 
> Doesn't it depend on the perspective? I guess I assumed the market price is derived from the actual value landing in Dao's wallet, after subtracting all costs.

Yeah, depends if we look from auction bids or DAO wallet perspective.

**Pull request merged**
